name: Miri

on:
  push:
    branches: [main]
  pull_request:

jobs:
  miri:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Miri
        run: rustup +nightly component add miri

      - name: Run Miri
        run: cargo +nightly miri test
